import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import { UIModeProvider } from "@/contexts/UIModeContext";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  style: "normal",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Apply the font class directly to the body */}
      <body className={`${spaceGrotesk.className} antialiased`}>
        <UIModeProvider>{children}</UIModeProvider>
      </body>
    </html>
  );
}
